# Generated by Django 4.2.1 on 2023-06-07 21:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('api_url', models.URLField()),
                ('logo_url', models.URLField(default='#')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('sale_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('added_date', models.DateField(default=datetime.datetime.utcnow)),
                ('for_date', models.DateField(default=datetime.datetime.utcnow)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency.exchangerateprovider')),
            ],
        ),
    ]
