# Generated by Django 4.2.1 on 2023-05-20 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='for_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
