# Generated by Django 4.2.1 on 2023-05-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_exchangerate_for_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerateprovider',
            name='logo_url',
            field=models.URLField(default='#'),
        ),
    ]
