# Generated by Django 4.2.1 on 2023-05-22 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_exchangerateprovider_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='for_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
