# Generated by Django 4.2.1 on 2023-05-26 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_exchangerate_added_date_alter_exchangerate_for_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='added_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
