# Generated by Django 4.2.1 on 2023-05-27 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_exchangerate_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='for_date',
            field=models.CharField(default=datetime.datetime.utcnow, max_length=10),
        ),
    ]
