# Generated by Django 4.2.1 on 2023-05-27 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_alter_exchangerate_for_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='for_date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
